### ISSUE TITLE
"Mod" isn't "模组"

### ISSUE THREAD

**Issue by ghost** [Meow-J/Forge-Documentation-CN#8]
I am [Minecraft Forge translation Proofreader](https://crowdin.com/profile/Angrydog001), please replace "模组" with "Mod", because "Mod" shouldn't be translated in simplified Chinese.

**Comment by Krasjet** [comment]
@ri-char 我记得之前一直都是用的是「Mod」的，你写的部分可以帮忙检查下吗

**Comment by ri-char** [comment]
改好了
(全日制高中生,两周放一次假,久等了,不好意思)
